apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: pod-info
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki-stack
      version: 2.9.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
    grafana:
      enabled: true
